CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE "customer" (
	"id" text PRIMARY KEY, -- Phone
	"name" text NOT NULL,
	"email" text NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
    CONSTRAINT customer_email_unique
        UNIQUE (email),
    CONSTRAINT customer_email_check
        CHECK (email IS NULL OR email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

CREATE TABLE "product" (
	"id" text PRIMARY KEY,
	"ean" bigint NOT NULL,
	"cat" text NOT NULL,
	"subcat" text DEFAULT 'Uncategorized' NULL,
	"name" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
    CONSTRAINT product_ean_unique
        UNIQUE (ean)
);

CREATE TABLE "orders" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"customer_id" text NOT NULL,
	"staff_id" text NOT NULL,
    "discount" numeric DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'completed' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
    CONSTRAINT orders_positive_discount
        CHECK (discount >= 0),
    CONSTRAINT orders_status_check
        CHECK (status IN ('completed', 'cancelled'))
);

CREATE TABLE "staff" (
	"id" text NOT NULL PRIMARY KEY,
	"name" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "item" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"order_id" bigint NOT NULL,
	"product_id" text NOT NULL,
	"serial" text NULL,
	"quantity" integer NOT NULL,
	"price" numeric NOT NULL,
    "discount" numeric DEFAULT 0 NOT NULL,
	CONSTRAINT item_quantity_check
        CHECK (quantity > 0),
    CONSTRAINT item_price_check
        CHECK (price >= 0),
    CONSTRAINT item_discount_check
        CHECK (discount >= 0)
);

CREATE TABLE "price" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"product_id" text NOT NULL,
	"price" numeric NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
    CONSTRAINT price_check_gt_zero
        CHECK (price > 0)
);

CREATE TABLE "payment" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"order_id" bigint NOT NULL,
	"method" text NOT NULL,
	"amount" numeric NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT payment_amount_check
        CHECK (amount > 0),
    CONSTRAINT payment_method_check
        CHECK (method IN ('cash', 'card', 'banking', 'vnpay', 'voucher'))
);

CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE TABLE "stock_ledger" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"product_id" text NOT NULL,
    "serial" TEXT NULL,
	"type" text NOT NULL,
	"quantity" bigint NOT NULL,
	"order_id" bigint NULL,
    "transaction_id" TEXT NULL,
    "batch_id" bigint NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT ledger_quantity_gt_zero
        CHECK (quantity > 0),
	CONSTRAINT ledger_type_check
        CHECK (type IN ('import_po', 'import_do', 'adjust_in', 'adjust_out', 'transfer', 'rtv', 'sell', 'return')),
    CONSTRAINT ledger_serial_consistency
        EXCLUDE USING gist(
            serial WITH = ,     -- 1 serial
            product_id WITH <>  -- Chỉ được đi cùng 1 product_id
        )
        WHERE (serial IS NOT NULL)
);


-- Index hỗ trợ tìm kiếm/lọc cho đơn hàng và chi tiết đơn hàng
CREATE INDEX "idx_order_customer" ON "orders" ("customer_id");
CREATE INDEX "idx_order_staff" ON "orders" ("staff_id");
CREATE INDEX "idx_item_order" ON "item" ("order_id");

-- Index cho bảng giá (Sửa logic: chỉ chặn trùng dòng nào đang hoạt động)
CREATE INDEX "idx_price_active" ON "price" ("product_id");
CREATE UNIQUE INDEX "idx_unique_active_price" ON "price" ("product_id") WHERE (is_active = true);

-- Index hỗ trợ kiểm kho
CREATE INDEX "idx_ledger_order" ON "stock_ledger" ("order_id");
CREATE INDEX "idx_ledger_product" ON "stock_ledger" ("product_id");

-- Index cho payment
CREATE INDEX "idx_payment_order_id" ON "payment" ("order_id");


-- FOREIGN KEYS
ALTER TABLE "payment" ADD CONSTRAINT "payment_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE;
ALTER TABLE "item" ADD CONSTRAINT "item_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE;
ALTER TABLE "item" ADD CONSTRAINT "item_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id");
ALTER TABLE "orders" ADD CONSTRAINT "order_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON UPDATE CASCADE;
ALTER TABLE "orders" ADD CONSTRAINT "order_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "staff"("id");
ALTER TABLE "price" ADD CONSTRAINT "price_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id");
ALTER TABLE "stock_ledger" ADD CONSTRAINT "stock_ledger_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE;
ALTER TABLE "stock_ledger" ADD CONSTRAINT "stock_ledger_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id");
ALTER TABLE "orders" ALTER COLUMN "id" RESTART WITH 10000000;

CREATE SEQUENCE ledger_batch_id_seq
    START WITH 10000000
    INCREMENT BY 1;
